# Generated by Django 3.2.8 on 2023-04-18 19:51

import app.core.utils.fields
import app.core.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', app.core.utils.fields.AppCharField(default=None, max_length=16, unique=True, verbose_name='Account number')),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('owner_first_name', app.core.utils.fields.AppCharField(blank=True, max_length=50, null=True, verbose_name='Firstname')),
                ('owner_last_name', app.core.utils.fields.AppCharField(blank=True, max_length=50, null=True, verbose_name='Lastname')),
                ('payment_qrcode_encrypted', app.core.utils.fields.AppCharField(blank=True, max_length=20, null=True, verbose_name='Payment Qr Code')),
                ('payment_qrcode_base64', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.CreateModel(
            name='AvailableCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', app.core.utils.fields.AppCharField(default=None, max_length=30)),
                ('dial_code', app.core.utils.fields.AppCharField(default=None, max_length=5, unique=True)),
                ('iso_code', app.core.utils.fields.AppCharField(default=None, max_length=10, unique=True)),
                ('phone_number_regex', app.core.utils.fields.AppCharField(default=None, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.CreateModel(
            name='PassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', app.core.utils.fields.AppCharField(default=None, max_length=20)),
                ('country_iso_code', app.core.utils.fields.AppCharField(default=None, max_length=2)),
                ('code', app.core.utils.fields.AppCharField(default=None, max_length=8)),
                ('sent_date', models.DateTimeField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('waiting_time', models.IntegerField(default=30)),
            ],
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', app.core.utils.fields.AppCharField(default=None, max_length=20)),
                ('primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('carrier', app.core.utils.fields.AppCharField(default=None, max_length=50, verbose_name='Carrier')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.account', verbose_name='Account')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.availablecountry')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.AddIndex(
            model_name='passcode',
            index=models.Index(fields=['phone_number', 'country_iso_code'], name='accounts_pa_phone_n_390f85_idx'),
        ),
    ]
