# Generated by Django 3.2.8 on 2023-05-19 16:26

import app.core.utils.fields
import app.core.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('phone_number', app.core.utils.fields.AppCharField(default=None, max_length=20, verbose_name='Phone Number')),
                ('intl_phone_number', app.core.utils.fields.AppCharField(default=None, max_length=20, verbose_name='Phone Number')),
                ('number', app.core.utils.fields.AppCharField(default=None, max_length=16, unique=True, verbose_name='Account number')),
                ('payment_code', app.core.utils.fields.AppCharField(blank=True, default=None, max_length=255, verbose_name='Payment Qr Code')),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('owner_first_name', app.core.utils.fields.AppCharField(blank=True, max_length=50, null=True, verbose_name='Firstname')),
                ('owner_last_name', app.core.utils.fields.AppCharField(blank=True, max_length=50, null=True, verbose_name='Lastname')),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.CreateModel(
            name='AvailableCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', app.core.utils.fields.AppCharField(default=None, max_length=50)),
                ('dial_code', app.core.utils.fields.AppCharField(default=None, max_length=5, unique=True)),
                ('iso_code', app.core.utils.fields.AppCharField(default=None, max_length=10, unique=True)),
                ('phone_number_regex', app.core.utils.fields.AppCharField(default=None, max_length=50)),
            ],
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.CreateModel(
            name='PassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('intl_phone_number', app.core.utils.fields.AppCharField(default=None, max_length=15)),
                ('code', app.core.utils.fields.AppCharField(default=None, max_length=8)),
                ('sent_on', models.DateTimeField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('next_passcode_on', models.DateTimeField()),
                ('next_verif_attempt_on', models.DateTimeField()),
                ('last_attempt_on', models.DateTimeField(null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('passcode_count', models.IntegerField(default=1)),
            ],
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('number', app.core.utils.fields.AppCharField(default=None, max_length=20)),
                ('primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=True)),
                ('carrier', app.core.utils.fields.AppCharField(default=None, max_length=50, verbose_name='Carrier')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.account', verbose_name='Account')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.AddIndex(
            model_name='passcode',
            index=models.Index(fields=['intl_phone_number'], name='accounts_pa_intl_ph_ce01cf_idx'),
        ),
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.availablecountry'),
        ),
        migrations.AddIndex(
            model_name='availablecountry',
            index=models.Index(fields=['iso_code'], name='accounts_av_iso_cod_5b08cd_idx'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.availablecountry'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['intl_phone_number'], name='accounts_ac_intl_ph_eb5656_idx'),
        ),
    ]
