# Generated by Django 3.2.8 on 2023-06-04 17:41

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=app.core.utils.fields.AppCharField(max_length=4, null=True, verbose_name='Pin code'),
        ),
    ]
