# Generated by Django 3.2.8 on 2023-04-21 17:12

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='payment_qrcode_base64',
        ),
        migrations.RemoveField(
            model_name='account',
            name='payment_qrcode_encrypted',
        ),
        migrations.AddField(
            model_name='account',
            name='payment_code',
            field=app.core.utils.fields.AppCharField(blank=True, default=None, max_length=255, verbose_name='Payment Qr Code'),
        ),
    ]
