# Generated by Django 3.2.8 on 2023-04-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='passcode_count',
            field=models.IntegerField(default=1),
        ),
    ]
