# Generated by Django 5.1.6 on 2025-03-13 23:25

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=app.core.utils.fields.AppCharField(blank=True, max_length=128, null=True, verbose_name='PIN'),
        ),
    ]
