# Generated by Django 5.1.6 on 2025-03-12 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, help_text="User's country, set during OTP verification", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.availablecountry'),
        ),
    ]
