# Generated by Django 3.2.8 on 2023-04-14 22:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='next_attempt_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 22, 48, 1, 538993, tzinfo=utc)),
        ),
    ]
