# Generated by Django 3.2.8 on 2023-04-07 20:19

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='network_supplier',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='carrier',
            field=app.core.utils.fields.AppCharField(default=None, max_length=50, verbose_name='Carrier'),
        ),
    ]
