# Generated by Django 3.2.8 on 2023-03-27 22:34

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecountry',
            name='phone_number_regex',
            field=app.core.utils.fields.AppCharField(default=None, max_length=50),
        ),
    ]
