# Generated by Django 3.2.8 on 2023-04-14 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_passcode_next_attempt_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='next_attempt_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 23, 6, 2, 965281, tzinfo=utc)),
        ),
    ]
