# Generated by Django 3.2.8 on 2023-04-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230407_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='passcode',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
