# Generated by Django 5.1.6 on 2025-04-23 02:38

import app.core.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, storage=app.core.utils.storage.ProfilePictureStorage(), upload_to='profile_pictures/'),
        ),
    ]
