# Generated by Django 3.2.8 on 2023-03-27 23:56

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_availablecountry_phone_number_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='country_iso_code',
            field=app.core.utils.fields.AppCharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='passcode',
            name='key',
            field=app.core.utils.fields.AppCharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='passcode',
            name='phone_number',
            field=app.core.utils.fields.AppCharField(default=None, max_length=20),
        ),
    ]
