# Generated by Django 3.2.8 on 2023-05-15 17:27

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecountry',
            name='name',
            field=app.core.utils.fields.AppCharField(default=None, max_length=50),
        ),
    ]
