# Generated by Django 5.1.6 on 2025-03-17 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currencies', to='accounts.availablecountry'),
        ),
    ]
