# Generated by Django 3.2.8 on 2021-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211110_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablecountry',
            old_name='code',
            new_name='calling_code',
        ),
        migrations.AddField(
            model_name='availablecountry',
            name='phone_number_regex',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
