# Generated by Django 3.2.8 on 2023-03-28 21:49

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230327_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='network_supplier',
            field=app.core.utils.fields.AppCharField(default=None, max_length=50, verbose_name='Network Supplier'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=app.core.utils.fields.AppCharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=app.core.utils.fields.AppCharField(max_length=50, null=True, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=app.core.utils.fields.AppCharField(max_length=50, null=True, verbose_name='Lastname'),
        ),
    ]
