# Generated by Django 5.1.6 on 2025-03-17 20:40

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_currency_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecountry',
            name='currency',
            field=app.core.utils.fields.AppCharField(blank=True, help_text='Default currency for this country (e.g., USD, EUR, XAF)', max_length=50, null=True, verbose_name='Currency'),
        ),
    ]
