# Generated by Django 5.1.6 on 2025-05-12 00:19

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecountry',
            name='flag',
            field=app.core.utils.fields.AppCharField(blank=True, help_text='Flag emoji for this country', max_length=10, null=True, verbose_name='Flag'),
        ),
    ]
