# Generated by Django 3.2.8 on 2023-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
