# Generated by Django 3.2.8 on 2021-11-27 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211125_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumberconfirmationcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phonenumberconfirmationcode',
            name='verified',
        ),
        migrations.AddField(
            model_name='phonenumberconfirmationcode',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounts.availablecountry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
