# Generated by Django 3.2.8 on 2023-04-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passcode_next_attempt_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='next_attempt_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
