# Generated by Django 3.2.8 on 2023-08-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_is_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='verified',
        ),
    ]
