# Generated by Django 3.2.8 on 2021-11-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211127_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='phonenumberconfirmationcode',
            name='key',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.networkprovider'),
        ),
    ]
