# Generated by Django 5.1.6 on 2025-05-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_availablecountry_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecountry',
            name='flag',
            field=models.ImageField(blank=True, help_text='Country flag image', null=True, upload_to='country_flags/', verbose_name='Flag'),
        ),
    ]
