# Generated by Django 3.2.8 on 2023-09-01 12:11

import app.core.utils.fields
import app.core.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_phonenumber_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedMobileMoneyCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', app.core.utils.fields.AppCharField(default=None, max_length=254, verbose_name='Name')),
                ('code', app.core.utils.fields.AppCharField(default=None, max_length=254, unique=True, verbose_name='Code')),
                ('flag', models.ImageField(upload_to='', verbose_name='Flag')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carriers', to='accounts.availablecountry')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='phonenumbers', to='accounts.supportedmobilemoneycarrier'),
        ),
    ]
