# Generated by Django 5.1.6 on 2025-05-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_availablecountry_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business',
            field=models.BooleanField(default=False, help_text='Designates whether this is a business account or a personal account.', verbose_name='business account'),
        ),
    ]
