# Generated by Django 5.1.6 on 2025-05-27 22:31

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_phone_number',
            field=app.core.utils.fields.AppCharField(blank=True, db_index=True, help_text='SHA-256 hash of the phone number', max_length=64, null=True, verbose_name='Hashed Phone Number'),
        ),
    ]
