# Generated by Django 3.2.8 on 2023-10-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230901_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
