# Generated by Django 3.2.8 on 2022-04-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumberconfirmationcode",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="phonenumberconfirmationcode",
            name="waiting_time",
            field=models.IntegerField(default=30),
        ),
    ]
