# Generated by Django 3.2.8 on 2024-01-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phonenumber_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='primary',
        ),
    ]
