# Generated by Django 5.1.6 on 2025-03-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240111_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassCode',
        ),
    ]
