volumes:
  vulipay_local_postgres_data: {}
  vulipay_local_postgres_data_backups: {}
  vulipay_local_redis_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: vulipay_local_django
    container_name: vulipay_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.redis
    ports:
      - "8000:8000"
      - "3000:3000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: vulipay_production_postgres
    container_name: vulipay_production_postgres
    volumes:
      - vulipay_local_postgres_data:/var/lib/postgresql/data:Z
      - vulipay_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5455:5432"

  redis:
    image: redis:7-alpine
    container_name: vulipay_redis
    volumes:
      - vulipay_local_redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redispassword
