# Generated by Django 5.1.6 on 2025-03-10 16:29

import app.core.utils.fields
import app.core.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('identifier', app.core.utils.fields.AppCharField(db_index=True, default=None, help_text='Phone number or email to identify the user', max_length=100)),
                ('code', app.core.utils.fields.AppCharField(default=None, max_length=10)),
                ('channel', app.core.utils.fields.AppCharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default=None, max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_otp_allowed_at', models.DateTimeField(blank=True, help_text='When the next OTP can be generated', null=True)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'indexes': [models.Index(fields=['identifier'], name='verify_otp_identif_10ce9e_idx'), models.Index(fields=['code'], name='verify_otp_code_651800_idx')],
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
    ]
