# Generated by Django 5.1.6 on 2025-03-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='next_otp_allowed_at',
            field=models.DateTimeField(blank=True, help_text='When the next OTP can be generated', null=True),
        ),
    ]
