# Generated by Django 3.2.8 on 2023-05-08 22:19

import app.core.utils.fields
import app.core.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reference', app.core.utils.fields.AppCharField(default=None, max_length=30, verbose_name='Reference')),
                ('payment_code', app.core.utils.fields.AppCharField(default=None, max_length=64, verbose_name='Payment code')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', app.core.utils.fields.AppCharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCEED', 'Succeed'), ('FAILED', 'Failed')], default=None, max_length=10, verbose_name='Status')),
                ('type', app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant payment'), ('CI', 'Cash In'), ('CO', 'Cash Out')], default=None, max_length=4, verbose_name='Type')),
                ('notes', models.TextField(null=True, verbose_name='Notes')),
                ('payer_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_transactions', to='accounts.account')),
                ('receiver_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
    ]
