# Generated by Django 5.1.6 on 2025-03-10 16:29

import app.core.utils.fields
import app.core.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reference', app.core.utils.fields.AppCharField(default=None, max_length=30, verbose_name='Reference')),
                ('payment_code', app.core.utils.fields.AppCharField(default=None, max_length=255, verbose_name='Payment code')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('charged_amount', models.FloatField(null=True, verbose_name='Charged Amount')),
                ('calculated_fee', models.FloatField(null=True, verbose_name='Calculated Fee')),
                ('status', app.core.utils.fields.AppCharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCEED', 'Succeed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default=None, max_length=10, verbose_name='Status')),
                ('type', app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant payment'), ('CI', 'Cash In'), ('CO', 'Cash Out')], default=None, max_length=4, verbose_name='Type')),
                ('notes', models.TextField(null=True, verbose_name='Notes')),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_transactions', to='accounts.account')),
                ('from_phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashin_transations', to='accounts.phonenumber')),
                ('payer_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_transactions', to='accounts.account')),
                ('receiver_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='accounts.account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashin_transactions', to='accounts.account')),
                ('to_phone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_transations', to='accounts.phonenumber')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('fee', models.FloatField()),
                ('transaction_type', app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant payment'), ('CI', 'Cash In'), ('CO', 'Cash Out')], default=None, max_length=10, verbose_name='Transaction Type')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.availablecountry')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
    ]
