# Generated by Django 3.2.8 on 2023-05-10 21:50

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_code',
            field=app.core.utils.fields.AppCharField(default=None, max_length=255, verbose_name='Payment code'),
        ),
    ]
