# Generated by Django 5.1.6 on 2025-03-17 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_currency_country'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for this wallet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='accounts.currency'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this wallet is active'),
        ),
    ]
