# Generated by Django 5.1.6 on 2025-03-10 21:29

import app.core.utils.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('card', 'Card'), ('mobile_money', 'Mobile Money')], max_length=50)),
                ('default_method', models.BooleanField(default=False)),
                ('cardholder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('masked_card_number', models.CharField(blank=True, max_length=19, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=7, null=True)),
                ('cvv_hash', models.TextField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
    ]
