# Generated by Django 5.1.6 on 2025-03-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethodtype',
            name='cash_in_transaction_fee',
        ),
        migrations.RemoveField(
            model_name='paymentmethodtype',
            name='cash_out_transaction_fee',
        ),
    ]
