# Generated by Django 5.1.6 on 2025-03-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_wallet_currency_alter_wallet_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency for this wallet (e.g., USD, EUR, XAF)', max_length=50, null=True),
        ),
    ]
