# Generated by Django 5.1.6 on 2025-03-10 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_paymentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, help_text='Name associated with the mobile money account (for mobile money payment methods)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Billing address associated with the card (for card payment methods)', null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(blank=True, help_text='Name of the cardholder (for card payment methods)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='cvv_hash',
            field=models.TextField(blank=True, help_text='Hashed CVV (not plaintext) for card payment methods', null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='default_method',
            field=models.BooleanField(default=False, help_text='Whether this is the default payment method for the user'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_date',
            field=models.CharField(blank=True, help_text='Card expiry date in MM/YYYY format (for card payment methods)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='masked_card_number',
            field=models.CharField(blank=True, help_text='Masked card number, e.g., **** **** **** 1234 (for card payment methods)', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number associated with the mobile money account (for mobile money payment methods)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(blank=True, help_text='Mobile money provider, e.g., M-Pesa, MTN Mobile Money (for mobile money payment methods)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('mobile_money', 'Mobile Money')], help_text='Type of payment method (card or mobile money)', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(help_text='User who owns this payment method', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
    ]
