# Generated by Django 5.1.6 on 2025-03-29 22:33

from django.db import migrations, models


def convert_both_to_fixed(apps, schema_editor):
    TransactionFee = apps.get_model("transactions", "TransactionFee")
    for fee in TransactionFee.objects.filter(fee_priority="both"):
        fee.fee_priority = "fixed"
        fee.percentage_fee = None
        fee.save()


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_transaction_fees_from_payment_method_type"),
    ]

    operations = [
        migrations.RunPython(convert_both_to_fixed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transactionfee",
            name="fee_priority",
            field=models.CharField(
                choices=[("fixed", "Fixed Fee"), ("percentage", "Percentage Fee")],
                default="percentage",
                max_length=20,
            ),
        ),
    ]
