# Generated by Django 3.2.8 on 2023-06-23 21:17

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20230622_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfee',
            name='transaction_type',
            field=app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant payment'), ('CI', 'Cash In'), ('CO', 'Cash Out')], default=None, max_length=10, verbose_name='Transaction Type'),
        ),
    ]
