# Generated by Django 3.2.8 on 2023-07-04 20:58

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactionfee_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=app.core.utils.fields.AppCharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCEED', 'Succeed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default=None, max_length=10, verbose_name='Status'),
        ),
    ]
