# Generated by Django 5.1.6 on 2025-03-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_both_fee_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodtype',
            name='allowed_transactions',
            field=models.JSONField(blank=True, help_text='List of transaction types allowed for this payment method', null=True, verbose_name='Allowed Transactions'),
        ),
    ]
