# Generated by Django 5.1.6 on 2025-03-17 20:36

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=app.core.utils.fields.AppCharField(blank=True, help_text='Currency for this wallet (e.g., USD, EUR, XAF)', max_length=50, null=True, verbose_name='Currency'),
        ),
    ]
