# Generated by Django 5.1.6 on 2025-03-11 23:14

import app.core.utils.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_paymentmethod_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=app.core.utils.fields.AppCharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default=None, max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant Payment'), ('CO', 'Cash Out'), ('CI', 'Cash In')], default=None, max_length=4, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='transaction_type',
            field=app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant Payment'), ('CO', 'Cash Out'), ('CI', 'Cash In')], default=None, max_length=10, verbose_name='Transaction Type'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current wallet balance', max_digits=12)),
                ('wallet_type', models.CharField(choices=[('MAIN', 'Main Wallet'), ('BUSINESS', 'Business Wallet')], default='MAIN', help_text='Type of wallet (Main or Business)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the wallet is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'unique_together': {('user', 'wallet_type')},
            },
        ),
    ]
