# Generated by Django 3.2.8 on 2023-10-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phonenumber_is_active'),
        ('transactions', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_transations', to='accounts.phonenumber'),
        ),
    ]
