# Generated by Django 5.1.6 on 2025-05-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_paymentmethodtype_allowed_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
