# Generated by Django 5.1.6 on 2025-03-12 00:07

import app.core.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_status_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(help_text='Payment method used for the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.paymentmethod'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(help_text='Wallet associated with the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant Payment'), ('CO', 'Cash Out'), ('CI', 'Cash In'), ('AF', 'Add Funds')], default=None, max_length=4, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='transaction_type',
            field=app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant Payment'), ('CO', 'Cash Out'), ('CI', 'Cash In'), ('AF', 'Add Funds')], default=None, max_length=10, verbose_name='Transaction Type'),
        ),
    ]
