# Generated by Django 5.1.6 on 2025-03-17 20:37

from django.db import migrations

import app.core.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_wallet_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="wallet_type",
            field=app.core.utils.fields.AppCharField(
                choices=[("MAIN", "Main Wallet"), ("BUSINESS", "Business Wallet")],
                default="MAIN",
                help_text="Type of wallet (Main or Business)",
                max_length=10,
                verbose_name="Wallet Type",
            ),
        ),
    ]
