# Generated by Django 5.1.6 on 2025-05-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_created_at_wallet_created_on_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionfee',
            unique_together=set(),
        ),
    ]
