# Generated by Django 5.1.6 on 2025-03-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_wallet_wallet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(help_text='Wallet associated with the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='transactions.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(help_text='Wallet associated with the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='transactions.wallet'),
        ),
    ]
