# Generated by Django 5.1.6 on 2025-03-12 19:43

import app.core.utils.fields
import app.core.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0005_transaction_payment_method_transaction_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant Payment'), ('CO', 'Cash Out'), ('CI', 'Cash In')], default=None, max_length=4, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='transaction_type',
            field=app.core.utils.fields.AppCharField(choices=[('P2P', 'Peer to Peer'), ('MP', 'Merchant Payment'), ('CO', 'Cash Out'), ('CI', 'Cash In')], default=None, max_length=10, verbose_name='Transaction Type'),
        ),
        migrations.CreateModel(
            name='PaymentMethodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', app.core.utils.fields.AppCharField(default=None, max_length=255, verbose_name='Name')),
                ('code', app.core.utils.fields.AppCharField(default=None, max_length=255, verbose_name='Code')),
                ('cash_in_transaction_fee', models.FloatField(null=True, verbose_name='Cash In Transaction Fee')),
                ('cash_out_transaction_fee', models.FloatField(null=True, verbose_name='Cash Out Transaction Fee')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.availablecountry')),
            ],
            options={
                'verbose_name': 'Payment Method Type',
                'verbose_name_plural': 'Payment Method Types',
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
    ]
