# Generated by Django 3.2.8 on 2023-10-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_phonenumber_is_active'),
        ('transactions', '0005_auto_20231012_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashin_transations', to='accounts.phonenumber'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashin_transactions', to='accounts.account'),
        ),
    ]
