# Generated by Django 5.1.6 on 2025-03-20 22:51

import app.core.utils.fields
import app.core.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_availablecountry_currency'),
        ('transactions', '0006_remove_transaction_payment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_wallet',
            field=models.ForeignKey(help_text='Wallet that sent the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='transactions.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(help_text='Wallet that received the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='transactions.wallet'),
        ),
        migrations.CreateModel(
            name='PlatformWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current wallet balance', max_digits=12)),
                ('currency', app.core.utils.fields.AppCharField(blank=True, help_text='Currency for this wallet (e.g., USD, EUR, XAF)', max_length=50, null=True, verbose_name='Currency')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.availablecountry')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, app.core.utils.models.ExtraModel),
        ),
    ]
