# Generated by Django 5.1.6 on 2025-05-11 04:11

from django.db import migrations, models

import app.core.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_remove_unique_constraint_from_transaction_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionfee",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="transactionfee",
            name="name",
            field=app.core.utils.fields.AppCharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
    ]
