# Generated by Django 5.1.6 on 2025-05-11 04:12

import app.core.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_populate_transaction_fee_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfee',
            name='name',
            field=app.core.utils.fields.AppCharField(default=None, max_length=255, verbose_name='Name'),
        ),
    ]
