# Generated by Django 5.1.6 on 2025-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transactionfee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfee',
            name='fixed_fee',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='percentage_fee',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
