# Generated by Django 5.1.6 on 2025-05-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transactionfee_fixed_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodtype',
            name='icon',
            field=models.ImageField(blank=True, help_text='Small icon representing the payment method (recommended size: 32x32px)', null=True, upload_to='payment_methods/icons/', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='paymentmethodtype',
            name='logo',
            field=models.ImageField(blank=True, help_text='Full logo of the payment method (recommended size: 200x100px)', null=True, upload_to='payment_methods/logos/', verbose_name='Logo'),
        ),
    ]
