name: Run Tests

on:
  push:
    branches: ['*']

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: docker compose -f local.yml build && docker compose -f local.yml up -d

      - name: Run tests
        run: docker compose -f local.yml exec -T django python manage.py test

      - name: Cleanup
        run: docker compose -f local.yml down
        if: always()
